package com.exileeconomics.definitions;


import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;


public enum ItemDefinitionEnum {
    WEALTH_AND_POWER("wealth and power", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    LUMINOUS_TROVE("luminous trove", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    SOMETHING_DARK("something dark", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    A_FAMILIAR_CALL("a familiar call", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ONE_THAT_GOT_AWAY("the one that got away", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    A_MODEST_REQUEST("a modest request", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ARTIST("the artist", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_STRATEGIST("the strategist", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_FISHMONGER("the fishmonger", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_NURSE("the nurse", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_LEVIATHAN("the leviathan", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_BITTER_BLOSSOM("the bitter blossom", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    CHOKING_GUILT("choking guilt", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_CHEATER("the cheater", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    IMPERFECT_MEMORIES("imperfect memories", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    PROMETHEUS_ARMOURY("prometheus' armoury", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    SUCCOR_OF_THE_SINLESS("succor of the sinless", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ASPIRANT("the aspirant", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_GULF("the gulf", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    HOME("home", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    DRAPED_IN_DREAMS("draped in dreams", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SCOUT("the scout", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    GIFT_OF_ASENATH("gift of asenath", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    UNREQUITED_LOVE("unrequited love", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_DOCTOR("the doctor", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ASTROMANCER("the astromancer", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    BEAUTY_THROUGH_DEATH("beauty through death", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_INSANE_CAT("the insane cat", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_AWAKENED("the awakened", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    ALLURING_BOUNTY("alluring bounty", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    REMEMBRANCE("remembrance", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    BROKEN_PROMISES("broken promises", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_FIEND("the fiend", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    HOUSE_OF_MIRRORS("house of mirrors", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    MONOCHROME("monochrome", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_VAST("the vast", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ENLIGHTENED("the enlightened", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_OLD_MAN("the old man", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    DARKER_HALF("darker half", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SHORTCUT("the shortcut", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    DIVINE_BEAUTY("divine beauty", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SOUL("the soul", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    BROTHERS_GIFT("brother's gift", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    DUALITY("duality", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    DORYANIS_EPIPHANY("doryani's epiphany", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    A_FATE_WORSE_THAN_DEATH("a fate worse than death", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ETERNAL_WAR("the eternal war", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    FRAGMENT_OF_ERADICATION("fragment of eradication", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SACRIFICE("the sacrifice", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_PRICE_OF_LOYALTY("the price of loyalty", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    SEVEN_YEARS_BAD_LUCK("seven years bad luck", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    WINTERS_EMBRACE("winter's embrace", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    ETERNAL_BONDS("eternal bonds", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    DESECRATED_VIRTUE("desecrated virtue", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_DRAGONS_HEART("the dragon's heart", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    REBIRTH("rebirth", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    LOVE_THROUGH_ICE("love through ice", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    MAGNUM_OPUS("magnum opus", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_TUMBLEWEED("the tumbleweed", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    FATEFUL_MEETING("fateful meeting", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_CHOSEN("the chosen", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SEPHIROT("the sephirot", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    MATRYOSHKA("matryoshka", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_EYE_OF_TERROR("the eye of terror", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_HOOK("the hook", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_DESTINATION("the destination", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_GARISH_POWER("the garish power", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    FURTHER_INVENTION("further invention", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ENDLESS_DARKNESS("the endless darkness", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    BROTHERS_STASH("brother's stash", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_PRICE_OF_DEVOTION("the price of devotion", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_IMMORTAL("the immortal", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_PATIENT("the patient", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_RABBITS_FOOT("the rabbit's foot", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_APOTHECARY("the apothecary", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SAMURAIS_EYE("the samurai's eye", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SHIELDBEARER("the shieldbearer", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    GEMCUTTERS_MERCY("gemcutter's mercy", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_GREATEST_INTENTIONS("the greatest intentions", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_LAST_ONE_STANDING("the last one standing", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_DEMON("the demon", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),

    WINGED_TORMENT_SCARAB("winged torment scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_SHAPER_SCARAB("gilded shaper scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_SULPHITE_SCARAB("winged sulphite scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_LEGION_SCARAB("gilded legion scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_BREACH_SCARAB("rusted breach scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_HARBINGER_SCARAB("winged harbinger scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_BLIGHT_SCARAB("rusted blight scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_METAMORPH_SCARAB("polished metamorph scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_TORMENT_SCARAB("gilded torment scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_EXPEDITION_SCARAB("winged expedition scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_LEGION_SCARAB("rusted legion scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_ELDER_SCARAB("rusted elder scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_CARTOGRAPHY_SCARAB("polished cartography scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_TORMENT_SCARAB("rusted torment scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_DIVINATION_SCARAB("rusted divination scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_AMBUSH_SCARAB("gilded ambush scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_DIVINATION_SCARAB("polished divination scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_SULPHITE_SCARAB("gilded sulphite scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_ELDER_SCARAB("gilded elder scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_ABYSS_SCARAB("polished abyss scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_LEGION_SCARAB("polished legion scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_RELIQUARY_SCARAB("gilded reliquary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_BLIGHT_SCARAB("winged blight scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_SHAPER_SCARAB("winged shaper scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    TORMENT_SCARAB("torment scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_DIVINATION_SCARAB("gilded divination scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_RELIQUARY_SCARAB("polished reliquary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_BESTIARY_SCARAB("winged bestiary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_ABYSS_SCARAB("rusted abyss scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_AMBUSH_SCARAB("rusted ambush scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_SHAPER_SCARAB("rusted shaper scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_ELDER_SCARAB("polished elder scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_ABYSS_SCARAB("gilded abyss scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_CARTOGRAPHY_SCARAB("winged cartography scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_LEGION_SCARAB("winged legion scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_BREACH_SCARAB("gilded breach scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_AMBUSH_SCARAB("polished ambush scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_SHAPER_SCARAB("polished shaper scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_BREACH_SCARAB("polished breach scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_METAMORPH_SCARAB("gilded metamorph scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_BLIGHT_SCARAB("polished blight scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_BESTIARY_SCARAB("gilded bestiary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_ABYSS_SCARAB("winged abyss scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_AMBUSH_SCARAB("winged ambush scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_HARBINGER_SCARAB("rusted harbinger scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_HARBINGER_SCARAB("gilded harbinger scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_SULPHITE_SCARAB("rusted sulphite scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_DIVINATION_SCARAB("winged divination scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_CARTOGRAPHY_SCARAB("rusted cartography scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_ELDER_SCARAB("winged elder scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_SULPHITE_SCARAB("polished sulphite scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_METAMORPH_SCARAB("rusted metamorph scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_RELIQUARY_SCARAB("winged reliquary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_EXPEDITION_SCARAB("polished expedition scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_EXPEDITION_SCARAB("rusted expedition scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_CARTOGRAPHY_SCARAB("gilded cartography scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_BESTIARY_SCARAB("polished bestiary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_BREACH_SCARAB("winged breach scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_EXPEDITION_SCARAB("gilded expedition scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_BESTIARY_SCARAB("rusted bestiary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_HARBINGER_SCARAB("polished harbinger scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_METAMORPH_SCARAB("winged metamorph scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_BLIGHT_SCARAB("gilded blight scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_RELIQUARY_SCARAB("rusted reliquary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),

    SCREAMING_ESSENCE_OF_ENVY("screaming essence of envy", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_ANGER("deafening essence of anger", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_HATRED("deafening essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_RAGE("screaming essence of rage", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_FEAR("screaming essence of fear", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_LOATHING("deafening essence of loathing", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_RAGE("weeping essence of rage", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_HATRED("shrieking essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_ENVY("deafening essence of envy", ItemDefinitionEnumCategoryMapper.ESSENCE),
    ESSENCE_OF_DELIRIUM("essence of delirium", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_FEAR("deafening essence of fear", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_ZEAL("shrieking essence of zeal", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_CONTEMPT("shrieking essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_WOE("wailing essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_WRATH("wailing essence of wrath", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_ANGUISH("shrieking essence of anguish", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_SUFFERING("shrieking essence of suffering", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_SCORN("deafening essence of scorn", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_DREAD("deafening essence of dread", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_RAGE("wailing essence of rage", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_WRATH("weeping essence of wrath", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_ANGER("wailing essence of anger", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_ANGER("screaming essence of anger", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_ZEAL("screaming essence of zeal", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_WOE("muttering essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_SUFFERING("deafening essence of suffering", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_CONTEMPT("muttering essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_SUFFERING("wailing essence of suffering", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_ANGER("muttering essence of anger", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_DREAD("shrieking essence of dread", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_DREAD("screaming essence of dread", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_FEAR("muttering essence of fear", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_SPITE("wailing essence of spite", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_WRATH("deafening essence of wrath", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_SPITE("shrieking essence of spite", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WHISPERING_ESSENCE_OF_GREED("whispering essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_SPITE("screaming essence of spite", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_ANGER("shrieking essence of anger", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_WOE("deafening essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_SORROW("wailing essence of sorrow", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_LOATHING("shrieking essence of loathing", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WHISPERING_ESSENCE_OF_WOE("whispering essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_ENVY("shrieking essence of envy", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_FEAR("shrieking essence of fear", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WHISPERING_ESSENCE_OF_HATRED("whispering essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_TORMENT("screaming essence of torment", ItemDefinitionEnumCategoryMapper.ESSENCE),
    ESSENCE_OF_HORROR("essence of horror", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_SUFFERING("screaming essence of suffering", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_GREED("muttering essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_SCORN("shrieking essence of scorn", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_SORROW("muttering essence of sorrow", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_ANGER("weeping essence of anger", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_TORMENT("shrieking essence of torment", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_DOUBT("screaming essence of doubt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_GREED("weeping essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_CONTEMPT("wailing essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_ZEAL("deafening essence of zeal", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_DOUBT("shrieking essence of doubt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_ANGUISH("deafening essence of anguish", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_WRATH("screaming essence of wrath", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_GREED("screaming essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_WRATH("shrieking essence of wrath", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_ANGUISH("wailing essence of anguish", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_SPITE("deafening essence of spite", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_TORMENT("weeping essence of torment", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_ANGUISH("screaming essence of anguish", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_FEAR("wailing essence of fear", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_TORMENT("wailing essence of torment", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_CONTEMPT("weeping essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_RAGE("deafening essence of rage", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_GREED("shrieking essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_GREED("wailing essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_DOUBT("weeping essence of doubt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_HATRED("wailing essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_SCORN("screaming essence of scorn", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_FEAR("weeping essence of fear", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_HATRED("muttering essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_HATRED("weeping essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_HATRED("screaming essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_ZEAL("wailing essence of zeal", ItemDefinitionEnumCategoryMapper.ESSENCE),
    ESSENCE_OF_INSANITY("essence of insanity", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_GREED("deafening essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_LOATHING("screaming essence of loathing", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WHISPERING_ESSENCE_OF_CONTEMPT("whispering essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_DOUBT("deafening essence of doubt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_WOE("screaming essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_RAGE("shrieking essence of rage", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_CONTEMPT("deafening essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_SORROW("shrieking essence of sorrow", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_MISERY("screaming essence of misery", ItemDefinitionEnumCategoryMapper.ESSENCE),
    ESSENCE_OF_HYSTERIA("essence of hysteria", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_WOE("weeping essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_TORMENT("muttering essence of torment", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_SORROW("screaming essence of sorrow", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_SORROW("weeping essence of sorrow", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_LOATHING("wailing essence of loathing", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_MISERY("deafening essence of misery", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_CONTEMPT("screaming essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_DOUBT("wailing essence of doubt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_SORROW("deafening essence of sorrow", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_SUFFERING("weeping essence of suffering", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_TORMENT("deafening essence of torment", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_WOE("shrieking essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_MISERY("shrieking essence of misery", ItemDefinitionEnumCategoryMapper.ESSENCE),
    REMNANT_OF_CORRUPTION("remnant of corruption", ItemDefinitionEnumCategoryMapper.ESSENCE),
    EXOTIC_COINAGE("exotic coinage", ItemDefinitionEnumCategoryMapper.ARTIFACT),
    BURIAL_MEDALLION("burial medallion", ItemDefinitionEnumCategoryMapper.ARTIFACT),
    SCRAP_METAL("scrap metal", ItemDefinitionEnumCategoryMapper.ARTIFACT),
    ASTRAGALI("astragali", ItemDefinitionEnumCategoryMapper.ARTIFACT),
    TAINTED_ORB_OF_FUSING("tainted orb of fusing", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    TAINTED_MYTHIC_ORB("tainted mythic orb", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    TAINTED_BLESSING("tainted blessing", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    TAINTED_CHAOS_ORB("tainted chaos orb", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    TAINTED_JEWELLERS_ORB("tainted jeweller's orb", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    TAINTED_OIL("tainted oil", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    TAINTED_EXALTED_ORB("tainted exalted orb", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    WILD_CRYSTALLISED_LIFEFORCE("wild crystallised lifeforce", ItemDefinitionEnumCategoryMapper.LIFEFORCE),
    PRIMAL_CRYSTALLISED_LIFEFORCE("primal crystallised lifeforce", ItemDefinitionEnumCategoryMapper.LIFEFORCE),
    SACRED_CRYSTALLISED_LIFEFORCE("sacred crystallised lifeforce", ItemDefinitionEnumCategoryMapper.LIFEFORCE),
    VIVID_CRYSTALLISED_LIFEFORCE("vivid crystallised lifeforce", ItemDefinitionEnumCategoryMapper.LIFEFORCE),
    AMORPHOUS_DELIRIUM_ORB("amorphous delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    BLIGHTED_DELIRIUM_ORB("blighted delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    FINE_DELIRIUM_ORB("fine delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    ABYSSAL_DELIRIUM_ORB("abyssal delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    OBSCURED_DELIRIUM_ORB("obscured delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    FOREBODING_DELIRIUM_ORB("foreboding delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    ARMOURSMITHS_DELIRIUM_ORB("armoursmith's delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    IMPERIAL_DELIRIUM_ORB("imperial delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    BLACKSMITHS_DELIRIUM_ORB("blacksmith's delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    THAUMATURGES_DELIRIUM_ORB("thaumaturge's delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    SKITTERING_DELIRIUM_ORB("skittering delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    FRAGMENTED_DELIRIUM_ORB("fragmented delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    DIVINERS_DELIRIUM_ORB("diviner's delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    SINGULAR_DELIRIUM_ORB("singular delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    FOSSILISED_DELIRIUM_ORB("fossilised delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    CARTOGRAPHERS_DELIRIUM_ORB("cartographer's delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    WHISPERING_DELIRIUM_ORB("whispering delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    TIMELESS_DELIRIUM_ORB("timeless delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    JEWELLERS_DELIRIUM_ORB("jeweller's delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    XOPHS_BREACHSTONE("xoph's breachstone", ItemDefinitionEnumCategoryMapper.BREACHSTONE),
    UULNETOLS_BREACHSTONE("uul-netol's breachstone", ItemDefinitionEnumCategoryMapper.BREACHSTONE),
    ESHS_BREACHSTONE("esh's breachstone", ItemDefinitionEnumCategoryMapper.BREACHSTONE),
    CHAYULAS_FLAWLESS_BREACHSTONE("chayula's flawless breachstone", ItemDefinitionEnumCategoryMapper.BREACHSTONE),
    TULS_BREACHSTONE("tul's breachstone", ItemDefinitionEnumCategoryMapper.BREACHSTONE),
    CHAYULAS_BREACHSTONE("chayula's breachstone", ItemDefinitionEnumCategoryMapper.BREACHSTONE),
    GOLDEN_OIL("golden oil", ItemDefinitionEnumCategoryMapper.OIL),
    OPALESCENT_OIL("opalescent oil", ItemDefinitionEnumCategoryMapper.OIL),
    BLACK_OIL("black oil", ItemDefinitionEnumCategoryMapper.OIL),
    CRIMSON_OIL("crimson oil", ItemDefinitionEnumCategoryMapper.OIL),
    SILVER_OIL("silver oil", ItemDefinitionEnumCategoryMapper.OIL),
    REFLECTIVE_OIL("reflective oil", ItemDefinitionEnumCategoryMapper.OIL),

    PRISTINE_FOSSIL("pristine fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    GLYPHIC_FOSSIL("glyphic fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    ABERRANT_FOSSIL("aberrant fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    PRISMATIC_FOSSIL("prismatic fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    DENSE_FOSSIL("dense fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    SCORCHED_FOSSIL("scorched fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    LUCENT_FOSSIL("lucent fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    BLOODSTAINED_FOSSIL("bloodstained fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    TANGLED_FOSSIL("tangled fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    METALLIC_FOSSIL("metallic fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    FACETED_FOSSIL("faceted fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    JAGGED_FOSSIL("jagged fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    SERRATED_FOSSIL("serrated fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    SANCTIFIED_FOSSIL("sanctified fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    BOUND_FOSSIL("bound fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    GILDED_FOSSIL("gilded fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    AETHERIC_FOSSIL("aetheric fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    SHUDDERING_FOSSIL("shuddering fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    FUNDAMENTAL_FOSSIL("fundamental fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    PERFECT_FOSSIL("perfect fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    FRIGID_FOSSIL("frigid fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    HOLLOW_FOSSIL("hollow fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    FRACTURED_FOSSIL("fractured fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    DEFT_FOSSIL("deft fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    CORRODED_FOSSIL("corroded fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    FRAGMENT_OF_ENSLAVEMENT("fragment of enslavement", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_THE_HYDRA("fragment of the hydra", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_THE_PHOENIX("fragment of the phoenix", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_PURIFICATION("fragment of purification", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_THE_CHIMERA("fragment of the chimera", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_TERROR("fragment of terror", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_EMPTINESS("fragment of emptiness", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_THE_MINOTAUR("fragment of the minotaur", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_SHAPE("fragment of shape", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_KNOWLEDGE("fragment of knowledge", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_CONSTRICTION("fragment of constriction", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    DROXS_CREST("drox's crest", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    BARANS_CREST("baran's crest", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    VERITANIAS_CREST("veritania's crest", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    ALHEZMINS_CREST("al-hezmin's crest", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    VIAL_OF_THE_GHOST("vial of the ghost", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_THE_RITUAL("vial of the ritual", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_SUMMONING("vial of summoning", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_AWAKENING("vial of awakening", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_CONSEQUENCE("vial of consequence", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_SACRIFICE("vial of sacrifice", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_TRANSCENDENCE("vial of transcendence", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_DOMINANCE("vial of dominance", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_FATE("vial of fate", ItemDefinitionEnumCategoryMapper.VIAL),

    //currency
    MIRROR_OF_KALANDRA("mirror of kalandra", ItemDefinitionEnumCategoryMapper.CURRENCY),
    CHAOS_ORB("chaos orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    MIRROR_SHARD("mirror shard", ItemDefinitionEnumCategoryMapper.CURRENCY),
    FRACTURING_ORB("fracturing orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    TEMPERING_ORB("tempering orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    TAINTED_DIVINE_TEARDROP("tainted divine teardrop", ItemDefinitionEnumCategoryMapper.CURRENCY),
    BLESSING_OF_CHAYULA("blessing of chayula", ItemDefinitionEnumCategoryMapper.CURRENCY),
    TAILORING_ORB("tailoring orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_DOMINANCE("orb of dominance", ItemDefinitionEnumCategoryMapper.CURRENCY),
    SECONDARY_REGRADING_LENS("secondary regrading lens", ItemDefinitionEnumCategoryMapper.CURRENCY),
    BLESSING_OF_ESH("blessing of esh", ItemDefinitionEnumCategoryMapper.CURRENCY),
    BLESSING_OF_TUL("blessing of tul", ItemDefinitionEnumCategoryMapper.CURRENCY),
    BLESSING_OF_XOPH("blessing of xoph", ItemDefinitionEnumCategoryMapper.CURRENCY),
    DIVINE_ORB("divine orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    HUNTERS_EXALTED_ORB("hunter's exalted orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    BLESSING_OF_UULNETOL("blessing of uul-netol", ItemDefinitionEnumCategoryMapper.CURRENCY),
    PRIME_REGRADING_LENS("prime regrading lens", ItemDefinitionEnumCategoryMapper.CURRENCY),
    SACRED_ORB("sacred orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    FRACTURING_SHARD("fracturing shard", ItemDefinitionEnumCategoryMapper.CURRENCY),
    OTHERWORLDLY_SCOUTING_REPORT("otherworldly scouting report", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_CONFLICT("orb of conflict", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ELEVATED_SEXTANT("elevated sextant", ItemDefinitionEnumCategoryMapper.CURRENCY),
    AWAKENERS_ORB("awakener's orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    REDEEMERS_EXALTED_ORB("redeemer's exalted orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    CRUSADERS_EXALTED_ORB("crusader's exalted orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    EXCEPTIONAL_ELDRITCH_EMBER("exceptional eldritch ember", ItemDefinitionEnumCategoryMapper.CURRENCY),
    EXCEPTIONAL_ELDRITCH_ICHOR("exceptional eldritch ichor", ItemDefinitionEnumCategoryMapper.CURRENCY),
    WARLORDS_EXALTED_ORB("warlord's exalted orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ELDRITCH_CHAOS_ORB("eldritch chaos orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ELDRITCH_ORB_OF_ANNULMENT("eldritch orb of annulment", ItemDefinitionEnumCategoryMapper.CURRENCY),
    EXALTED_ORB("exalted orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    COMPREHENSIVE_SCOUTING_REPORT("comprehensive scouting report", ItemDefinitionEnumCategoryMapper.CURRENCY),
    CHARGED_COMPASS("charged compass", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ELDRITCH_EXALTED_ORB("eldritch exalted orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    OIL_EXTRACTOR("oil extractor", ItemDefinitionEnumCategoryMapper.CURRENCY),
    PRISMATIC_CATALYST("prismatic catalyst", ItemDefinitionEnumCategoryMapper.CATALYST),
    VEILED_CHAOS_ORB("veiled chaos orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_ANNULMENT("orb of annulment", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ANCIENT_ORB("ancient orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    UNSTABLE_CATALYST("unstable catalyst", ItemDefinitionEnumCategoryMapper.CATALYST),
    RITUAL_VESSEL("ritual vessel", ItemDefinitionEnumCategoryMapper.CURRENCY),
    BLIGHTED_SCOUTING_REPORT("blighted scouting report", ItemDefinitionEnumCategoryMapper.CURRENCY),
    GRAND_ELDRITCH_EMBER("grand eldritch ember", ItemDefinitionEnumCategoryMapper.CURRENCY),
    AWAKENED_SEXTANT("awakened sextant", ItemDefinitionEnumCategoryMapper.CURRENCY),
    GRAND_ELDRITCH_ICHOR("grand eldritch ichor", ItemDefinitionEnumCategoryMapper.CURRENCY),
    INFLUENCED_SCOUTING_REPORT("influenced scouting report", ItemDefinitionEnumCategoryMapper.CURRENCY),
    TAINTED_CHROMATIC_ORB("tainted chromatic orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    FERTILE_CATALYST("fertile catalyst", ItemDefinitionEnumCategoryMapper.CATALYST),
    STACKED_DECK("stacked deck", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ACCELERATING_CATALYST("accelerating catalyst", ItemDefinitionEnumCategoryMapper.CATALYST),
    DELIRIOUS_SCOUTING_REPORT("delirious scouting report", ItemDefinitionEnumCategoryMapper.CURRENCY),
    SINGULAR_SCOUTING_REPORT("singular scouting report", ItemDefinitionEnumCategoryMapper.CURRENCY),
    SURVEYORS_COMPASS("surveyor's compass", ItemDefinitionEnumCategoryMapper.CURRENCY),
    HARBINGERS_ORB("harbinger's orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ANNULMENT_SHARD("annulment shard", ItemDefinitionEnumCategoryMapper.CURRENCY),
    EXALTED_SHARD("exalted shard", ItemDefinitionEnumCategoryMapper.CURRENCY),
    TAINTED_ARMOURERS_SCRAP("tainted armourer's scrap", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_SCOURING("orb of scouring", ItemDefinitionEnumCategoryMapper.CURRENCY),
    GREATER_ELDRITCH_EMBER("greater eldritch ember", ItemDefinitionEnumCategoryMapper.CURRENCY),
    GREATER_ELDRITCH_ICHOR("greater eldritch ichor", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_UNMAKING("orb of unmaking", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ENKINDLING_ORB("enkindling orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    VAAL_ORB("vaal orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    GEMCUTTERS_PRISM("gemcutter's prism", ItemDefinitionEnumCategoryMapper.CURRENCY),
    EXPLORERS_SCOUTING_REPORT("explorer's scouting report", ItemDefinitionEnumCategoryMapper.CURRENCY),
    INTRINSIC_CATALYST("intrinsic catalyst", ItemDefinitionEnumCategoryMapper.CATALYST),
    NOXIOUS_CATALYST("noxious catalyst", ItemDefinitionEnumCategoryMapper.CATALYST),
    REGAL_ORB("regal orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    TEMPERING_CATALYST("tempering catalyst", ItemDefinitionEnumCategoryMapper.CATALYST),
    VAAL_SCOUTING_REPORT("vaal scouting report", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_REGRET("orb of regret", ItemDefinitionEnumCategoryMapper.CURRENCY),
    BLESSED_ORB("blessed orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    TURBULENT_CATALYST("turbulent catalyst", ItemDefinitionEnumCategoryMapper.CATALYST),
    TAINTED_BLACKSMITHS_WHETSTONE("tainted blacksmith's whetstone", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_FUSING("orb of fusing", ItemDefinitionEnumCategoryMapper.CURRENCY),
    LESSER_ELDRITCH_ICHOR("lesser eldritch ichor", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_HORIZONS("orb of horizons", ItemDefinitionEnumCategoryMapper.CURRENCY),
    GLASSBLOWERS_BAUBLE("glassblower's bauble", ItemDefinitionEnumCategoryMapper.CURRENCY),
    INSTILLING_ORB("instilling orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ABRASIVE_CATALYST("abrasive catalyst", ItemDefinitionEnumCategoryMapper.CATALYST),
    ORB_OF_CHANCE("orb of chance", ItemDefinitionEnumCategoryMapper.CURRENCY),
    CARTOGRAPHERS_CHISEL("cartographer's chisel", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ENGINEERS_ORB("engineer's orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    IMBUED_CATALYST("imbued catalyst", ItemDefinitionEnumCategoryMapper.CATALYST),
    LESSER_ELDRITCH_EMBER("lesser eldritch ember", ItemDefinitionEnumCategoryMapper.CURRENCY),
    CHROMATIC_ORB("chromatic orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_ALTERATION("orb of alteration", ItemDefinitionEnumCategoryMapper.CURRENCY),
    JEWELLERS_ORB("jeweller's orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_AUGMENTATION("orb of augmentation", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_ALCHEMY("orb of alchemy", ItemDefinitionEnumCategoryMapper.CURRENCY),
    PORTAL_SCROLL("portal scroll", ItemDefinitionEnumCategoryMapper.CURRENCY),
    BLACKSMITHS_WHETSTONE("blacksmith's whetstone", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_BINDING("orb of binding", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_TRANSMUTATION("orb of transmutation", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ARMOURERS_SCRAP("armourer's scrap", ItemDefinitionEnumCategoryMapper.CURRENCY),
    SCROLL_OF_WISDOM("scroll of wisdom", ItemDefinitionEnumCategoryMapper.CURRENCY),
    MAVENS_ORB("maven's orb", ItemDefinitionEnumCategoryMapper.CURRENCY),

    // incubators
    ORNATE_INCUBATOR("ornate incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    DIVINERS_INCUBATOR("diviner's incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    CELESTIAL_ARMOURSMITHS_INCUBATOR("celestial armoursmith's incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    KALGUURAN_INCUBATOR("kalguuran incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    FRAGMENTED_INCUBATOR("fragmented incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    CELESTIAL_JEWELLERS_INCUBATOR("celestial jeweller's incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    CARTOGRAPHERS_INCUBATOR("cartographer's incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    MYSTERIOUS_INCUBATOR("mysterious incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    OBSCURED_INCUBATOR("obscured incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    OTHERWORLDLY_INCUBATOR("otherworldly incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    SKITTERING_INCUBATOR("skittering incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    INFUSED_INCUBATOR("infused incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    GEOMANCERS_INCUBATOR("geomancer's incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    THAUMATURGES_INCUBATOR("thaumaturge's incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    FOREBODING_INCUBATOR("foreboding incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    CELESTIAL_BLACKSMITHS_INCUBATOR("celestial blacksmith's incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    MADDENING_INCUBATOR("maddening incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    SINGULAR_INCUBATOR("singular incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    ABYSSAL_INCUBATOR("abyssal incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    BLIGHTED_INCUBATOR("blighted incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    ENCHANTED_INCUBATOR("enchanted incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    FOSSILISED_INCUBATOR("fossilised incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    MORPHING_INCUBATOR("morphing incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),
    PRIMAL_INCUBATOR("primal incubator", ItemDefinitionEnumCategoryMapper.INCUBATOR),

    //invitations
    SCREAMING_INVITATION("screaming invitation", ItemDefinitionEnumCategoryMapper.INVITATION),
    INCANDESCENT_INVITATION("incandescent invitation", ItemDefinitionEnumCategoryMapper.INVITATION),
    MAVENS_INVITATION_THE_FORMED("maven's invitation: the formed", ItemDefinitionEnumCategoryMapper.INVITATION),
    MAVENS_INVITATION_THE_ELDERSLAYERS("maven's invitation: the elderslayers", ItemDefinitionEnumCategoryMapper.INVITATION),
    MAVENS_INVITATION_THE_TWISTED("maven's invitation: the twisted", ItemDefinitionEnumCategoryMapper.INVITATION),
    MAVENS_INVITATION_THE_FEARED("maven's invitation: the feared", ItemDefinitionEnumCategoryMapper.INVITATION),
    MAVENS_INVITATION_THE_FORGOTTEN("maven's invitation: the forgotten", ItemDefinitionEnumCategoryMapper.INVITATION),
    MAVENS_INVITATION_THE_HIDDEN("maven's invitation: the hidden", ItemDefinitionEnumCategoryMapper.INVITATION),
    POLARIC_INVITATION("polaric invitation", ItemDefinitionEnumCategoryMapper.INVITATION),
    WRITHING_INVITATION("writhing invitation", ItemDefinitionEnumCategoryMapper.INVITATION),
    MAVENS_INVITATION_THE_ATLAS("maven's invitation: the atlas", ItemDefinitionEnumCategoryMapper.INVITATION),

    // beasts
    ELDERBLESSED_RHOA("elder-blessed rhoa", ItemDefinitionEnumCategoryMapper.BEAST),
    CRAICIC_CHIMERAL("craicic chimeral", ItemDefinitionEnumCategoryMapper.BEAST),
    VIVID_VULTURE("vivid vulture", ItemDefinitionEnumCategoryMapper.BEAST),
    WILD_BRISTLE_MATRON("wild bristle matron", ItemDefinitionEnumCategoryMapper.BEAST),
    WILD_HELLION_ALPHA("wild hellion alpha", ItemDefinitionEnumCategoryMapper.BEAST),
    FENUMAL_PLAGUED_ARACHNID("fenumal plagued arachnid", ItemDefinitionEnumCategoryMapper.BEAST),
    WAR_HOUND("war hound", ItemDefinitionEnumCategoryMapper.BEAST),
    VIVID_WATCHER("vivid watcher", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRUL_FIRST_OF_THE_PLAINS("farrul, first of the plains", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_FROST_HELLION_ALPHA("farric frost hellion alpha", ItemDefinitionEnumCategoryMapper.BEAST),
    FENUMUS_FIRST_OF_THE_NIGHT("fenumus, first of the night", ItemDefinitionEnumCategoryMapper.BEAST),
    WILD_BRAMBLEBACK("wild brambleback", ItemDefinitionEnumCategoryMapper.BEAST),
    ELDERBLESSED_COBRA("elder-blessed cobra", ItemDefinitionEnumCategoryMapper.BEAST),
    ELDERBLESSED_HELLION("elder-blessed hellion", ItemDefinitionEnumCategoryMapper.BEAST),
    ARCTIC_WOLF("arctic wolf", ItemDefinitionEnumCategoryMapper.BEAST),
    GOATMAN_FIRERAISER("goatman fire-raiser", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_TIGER_ALPHA("farric tiger alpha", ItemDefinitionEnumCategoryMapper.BEAST),
    MERVEILS_ATTENDANT("merveil's attendant", ItemDefinitionEnumCategoryMapper.BEAST),
    PRIMAL_CRUSHCLAW("primal crushclaw", ItemDefinitionEnumCategoryMapper.BEAST),
    PRIMAL_CYSTCALLER("primal cystcaller", ItemDefinitionEnumCategoryMapper.BEAST),
    VIVID_ABBERARACH("vivid abberarach", ItemDefinitionEnumCategoryMapper.BEAST),
    MERVEILS_DAUGHTER("merveil's daughter", ItemDefinitionEnumCategoryMapper.BEAST),
    MUTANT_ARACH("mutant arach", ItemDefinitionEnumCategoryMapper.BEAST),
    CRAICIC_VASSAL("craicic vassal", ItemDefinitionEnumCategoryMapper.BEAST),
    SWARTHY_MOLLUSC("swarthy mollusc", ItemDefinitionEnumCategoryMapper.BEAST),
    ELDERBLESSED_RETCH("elder-blessed retch", ItemDefinitionEnumCategoryMapper.BEAST),
    CRAICIC_MAW("craicic maw", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_WOLF_ALPHA("farric wolf alpha", ItemDefinitionEnumCategoryMapper.BEAST),
    FENUMAL_HYBRID_ARACHNID("fenumal hybrid arachnid", ItemDefinitionEnumCategoryMapper.BEAST),
    PRIMAL_RHEX_MATRIARCH("primal rhex matriarch", ItemDefinitionEnumCategoryMapper.BEAST),
    SAQAWAL_FIRST_OF_THE_SKY("saqawal, first of the sky", ItemDefinitionEnumCategoryMapper.BEAST),
    CRAICEANN_FIRST_OF_THE_DEEP("craiceann, first of the deep", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_LYNX_ALPHA("farric lynx alpha", ItemDefinitionEnumCategoryMapper.BEAST),
    FENUMAL_SCORPION("fenumal scorpion", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_APE("farric ape", ItemDefinitionEnumCategoryMapper.BEAST),
    CRAICIC_SAVAGE_CRAB("craicic savage crab", ItemDefinitionEnumCategoryMapper.BEAST),
    CRAICIC_SPIDER_CRAB("craicic spider crab", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_PIT_HOUND("farric pit hound", ItemDefinitionEnumCategoryMapper.BEAST),
    HOST_CHIEFTAIN("host chieftain", ItemDefinitionEnumCategoryMapper.BEAST),
    SAQAWINE_RHEX("saqawine rhex", ItemDefinitionEnumCategoryMapper.BEAST),
    SAQAWINE_VULTURE("saqawine vulture", ItemDefinitionEnumCategoryMapper.BEAST),
    VICIOUS_PARASITE("vicious parasite", ItemDefinitionEnumCategoryMapper.BEAST),
    INFESTED_VULTURE("infested vulture", ItemDefinitionEnumCategoryMapper.BEAST),
    THICKET_HULK("thicket hulk", ItemDefinitionEnumCategoryMapper.BEAST),
    GOATMAN("goatman", ItemDefinitionEnumCategoryMapper.BEAST),
    SAND_SCORPION("sand scorpion", ItemDefinitionEnumCategoryMapper.BEAST),
    FERAL_CHIMERAL("feral chimeral", ItemDefinitionEnumCategoryMapper.BEAST),
    ENRAPTURED_ARACHNID("enraptured arachnid", ItemDefinitionEnumCategoryMapper.BEAST),
    SAND_SKITTERER("sand skitterer", ItemDefinitionEnumCategoryMapper.BEAST),
    SCALDING_ARACHNID("scalding arachnid", ItemDefinitionEnumCategoryMapper.BEAST),
    VAULTING_CROAKER("vaulting croaker", ItemDefinitionEnumCategoryMapper.BEAST),
    ACID_SLITHERER("acid slitherer", ItemDefinitionEnumCategoryMapper.BEAST),
    ADOLESCENT_RHEX("adolescent rhex", ItemDefinitionEnumCategoryMapper.BEAST),
    ALPINE_DEVIL("alpine devil", ItemDefinitionEnumCategoryMapper.BEAST),
    ALPINE_SHAMAN("alpine shaman", ItemDefinitionEnumCategoryMapper.BEAST),
    ARAKAALIS_DAUGHTER("arakaali's daughter", ItemDefinitionEnumCategoryMapper.BEAST),
    ARMOUR_CRUNCHER("armour cruncher", ItemDefinitionEnumCategoryMapper.BEAST),
    AVALANCHE_RIDER("avalanche rider", ItemDefinitionEnumCategoryMapper.BEAST),
    AVIAN_RETCH("avian retch", ItemDefinitionEnumCategoryMapper.BEAST),
    BARB_SERPENT("barb serpent", ItemDefinitionEnumCategoryMapper.BEAST),
    BARROW_APE("barrow ape", ItemDefinitionEnumCategoryMapper.BEAST),
    BEARDED_DEVIL("bearded devil", ItemDefinitionEnumCategoryMapper.BEAST),
    BEARDED_SHAMAN("bearded shaman", ItemDefinitionEnumCategoryMapper.BEAST),
    BEARDED_SKYCALLER("bearded skycaller", ItemDefinitionEnumCategoryMapper.BEAST),
    BLACK_SCORPION("black scorpion", ItemDefinitionEnumCategoryMapper.BEAST),
    BLEACHED_CRAWLER("bleached crawler", ItemDefinitionEnumCategoryMapper.BEAST),
    BLOOD_APE("blood ape", ItemDefinitionEnumCategoryMapper.BEAST),
    BLOOD_CHIEFTAIN("blood chieftain", ItemDefinitionEnumCategoryMapper.BEAST),
    BONE_RHOA("bone rhoa", ItemDefinitionEnumCategoryMapper.BEAST),
    BRAMBLE_COBRA("bramble cobra", ItemDefinitionEnumCategoryMapper.BEAST),
    BRINE_VASSAL("brine vassal", ItemDefinitionEnumCategoryMapper.BEAST),
    CARNAGE_APE("carnage ape", ItemDefinitionEnumCategoryMapper.BEAST),
    CARNAGE_CHIEFTAIN("carnage chieftain", ItemDefinitionEnumCategoryMapper.BEAST),
    CARRION_BURROWER("carrion burrower", ItemDefinitionEnumCategoryMapper.BEAST),
    CARRION_QUEEN("carrion queen", ItemDefinitionEnumCategoryMapper.BEAST),
    CARRION_SWARMER("carrion swarmer", ItemDefinitionEnumCategoryMapper.BEAST),
    CAVE_BEAST("cave beast", ItemDefinitionEnumCategoryMapper.BEAST),
    CAVE_SKITTERER("cave skitterer", ItemDefinitionEnumCategoryMapper.BEAST),
    CHIMERIC_CROAKER("chimeric croaker", ItemDefinitionEnumCategoryMapper.BEAST),
    CHROMEINFUSED_CHIMERAL("chrome-infused chimeral", ItemDefinitionEnumCategoryMapper.BEAST),
    CHROMEINFUSED_CROAKER("chrome-infused croaker", ItemDefinitionEnumCategoryMapper.BEAST),
    CHROMEINFUSED_GOLIATH("chrome-infused goliath", ItemDefinitionEnumCategoryMapper.BEAST),
    CHROMETOUCHED_CHIMERAL("chrome-touched chimeral", ItemDefinitionEnumCategoryMapper.BEAST),
    CHROMETOUCHED_CROAKER("chrome-touched croaker", ItemDefinitionEnumCategoryMapper.BEAST),
    CHROMETOUCHED_GOLIATH("chrome-touched goliath", ItemDefinitionEnumCategoryMapper.BEAST),
    COLOSSUS_CRUSHER("colossus crusher", ItemDefinitionEnumCategoryMapper.BEAST),
    CORRUPTED_ARACH("corrupted arach", ItemDefinitionEnumCategoryMapper.BEAST),
    CORRUPTED_BEAST("corrupted beast", ItemDefinitionEnumCategoryMapper.BEAST),
    CORRUPTED_RHOA("corrupted rhoa", ItemDefinitionEnumCategoryMapper.BEAST),
    CRAICIC_SHIELD_CRAB("craicic shield crab", ItemDefinitionEnumCategoryMapper.BEAST),
    CRAICIC_WATCHER("craicic watcher", ItemDefinitionEnumCategoryMapper.BEAST),
    CRUSTACEAN_SNIPER("crustacean sniper", ItemDefinitionEnumCategoryMapper.BEAST),
    CURSED_SPAWN("cursed spawn", ItemDefinitionEnumCategoryMapper.BEAST),
    DEVOURER("devourer", ItemDefinitionEnumCategoryMapper.BEAST),
    DIRT_SCRABBLER("dirt scrabbler", ItemDefinitionEnumCategoryMapper.BEAST),
    DUNE_HELLION("dune hellion", ItemDefinitionEnumCategoryMapper.BEAST),
    DUST_SCRABBLER("dust scrabbler", ItemDefinitionEnumCategoryMapper.BEAST),
    ELDERBLESSED_GOATMAN("elder-blessed goatman", ItemDefinitionEnumCategoryMapper.BEAST),
    ENRAPTURED_BEAST("enraptured beast", ItemDefinitionEnumCategoryMapper.BEAST),
    ESCAPED_RHEX("escaped rhex", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_CHIEFTAIN("farric chieftain", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_FLAME_HELLION_ALPHA("farric flame hellion alpha", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_GOATMAN("farric goatman", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_GOLIATH("farric goliath", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_MAGMA_HOUND("farric magma hound", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_TAURUS("farric taurus", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_URSA("farric ursa", ItemDefinitionEnumCategoryMapper.BEAST),
    FENUMAL_DEVOURER("fenumal devourer", ItemDefinitionEnumCategoryMapper.BEAST),
    FENUMAL_QUEEN("fenumal queen", ItemDefinitionEnumCategoryMapper.BEAST),
    FENUMAL_WIDOW("fenumal widow", ItemDefinitionEnumCategoryMapper.BEAST),
    FETID_MAW("fetid maw", ItemDefinitionEnumCategoryMapper.BEAST),
    FIGHTING_BULL("fighting bull", ItemDefinitionEnumCategoryMapper.BEAST),
    FILTH_MAW("filth maw", ItemDefinitionEnumCategoryMapper.BEAST),
    FLAME_HELLION("flame hellion", ItemDefinitionEnumCategoryMapper.BEAST),
    FOREST_BEAST("forest beast", ItemDefinitionEnumCategoryMapper.BEAST),
    FREEZING_WOLF("freezing wolf", ItemDefinitionEnumCategoryMapper.BEAST),
    FURY_HOUND("fury hound", ItemDefinitionEnumCategoryMapper.BEAST),
    GLADE_MAMBA("glade mamba", ItemDefinitionEnumCategoryMapper.BEAST),
    GLUTTONOUS_GULL("gluttonous gull", ItemDefinitionEnumCategoryMapper.BEAST),
    GOATMAN_SHAMAN("goatman shaman", ItemDefinitionEnumCategoryMapper.BEAST),
    GRANITE_EATER("granite eater", ItemDefinitionEnumCategoryMapper.BEAST),
    GRAVEL_EATER("gravel eater", ItemDefinitionEnumCategoryMapper.BEAST),
    GRAZING_TAURUS("grazing taurus", ItemDefinitionEnumCategoryMapper.BEAST),
    HAIRY_BONECRUNCHER("hairy bonecruncher", ItemDefinitionEnumCategoryMapper.BEAST),
    HILL_DEVIL("hill devil", ItemDefinitionEnumCategoryMapper.BEAST),
    HOST_ADDER("host adder", ItemDefinitionEnumCategoryMapper.BEAST),
    HOST_COBRA("host cobra", ItemDefinitionEnumCategoryMapper.BEAST),
    HYBRID_ARACHNID("hybrid arachnid", ItemDefinitionEnumCategoryMapper.BEAST),
    INFESTED_APE("infested ape", ItemDefinitionEnumCategoryMapper.BEAST),
    INFESTED_CRAB("infested crab", ItemDefinitionEnumCategoryMapper.BEAST),
    INFESTED_CRAWLER("infested crawler", ItemDefinitionEnumCategoryMapper.BEAST),
    INFESTED_MAW("infested maw", ItemDefinitionEnumCategoryMapper.BEAST),
    INFESTED_RHOA("infested rhoa", ItemDefinitionEnumCategoryMapper.BEAST),
    INFESTED_SKITTERER("infested skitterer", ItemDefinitionEnumCategoryMapper.BEAST),
    INFESTED_TUNNELFIEND("infested tunnelfiend", ItemDefinitionEnumCategoryMapper.BEAST),
    INK_SPINNER("ink spinner", ItemDefinitionEnumCategoryMapper.BEAST),
    LEAPING_SPIDER("leaping spider", ItemDefinitionEnumCategoryMapper.BEAST),
    MATERNAL_RHEX("maternal rhex", ItemDefinitionEnumCategoryMapper.BEAST),
    MERVEILS_BLESSED("merveil's blessed", ItemDefinitionEnumCategoryMapper.BEAST),
    MERVEILS_CHOSEN("merveil's chosen", ItemDefinitionEnumCategoryMapper.BEAST),
    MERVEILS_FAVOURED("merveil's favoured", ItemDefinitionEnumCategoryMapper.BEAST),
    MERVEILS_RETAINER("merveil's retainer", ItemDefinitionEnumCategoryMapper.BEAST),
    MINDLESS_SCAVENGER("mindless scavenger", ItemDefinitionEnumCategoryMapper.BEAST),
    MOUNTAIN_HELLION("mountain hellion", ItemDefinitionEnumCategoryMapper.BEAST),
    MOUNTAIN_HELLION_ALPHA("mountain hellion alpha", ItemDefinitionEnumCategoryMapper.BEAST),
    MOUNTAIN_LYNX("mountain lynx", ItemDefinitionEnumCategoryMapper.BEAST),
    MURK_RUNNER("murk runner", ItemDefinitionEnumCategoryMapper.BEAST),
    NIGHT_ADDER("night adder", ItemDefinitionEnumCategoryMapper.BEAST),
    NOXIOUS_TARANTULA("noxious tarantula", ItemDefinitionEnumCategoryMapper.BEAST),
    OBSIDIAN_EATER("obsidian eater", ItemDefinitionEnumCategoryMapper.BEAST),
    PITBULL_DEMON("pitbull demon", ItemDefinitionEnumCategoryMapper.BEAST),
    PLAGUED_ARACHNID("plagued arachnid", ItemDefinitionEnumCategoryMapper.BEAST),
    PLUMED_CHIMERAL("plumed chimeral", ItemDefinitionEnumCategoryMapper.BEAST),
    PLUMMETING_URSA("plummeting ursa", ItemDefinitionEnumCategoryMapper.BEAST),
    PORCUPINE_GOLIATH("porcupine goliath", ItemDefinitionEnumCategoryMapper.BEAST),
    PREDATORY_SCORPION("predatory scorpion", ItemDefinitionEnumCategoryMapper.BEAST),
    PURGE_HOUND("purge hound", ItemDefinitionEnumCategoryMapper.BEAST),
    RHOA_MARE("rhoa mare", ItemDefinitionEnumCategoryMapper.BEAST),
    ROCK_SPITTER("rock spitter", ItemDefinitionEnumCategoryMapper.BEAST),
    ROOSTER_FIEND("rooster fiend", ItemDefinitionEnumCategoryMapper.BEAST),
    SAND_LEAPER("sand leaper", ItemDefinitionEnumCategoryMapper.BEAST),
    SAQAWINE_BLOOD_VIPER("saqawine blood viper", ItemDefinitionEnumCategoryMapper.BEAST),
    SAQAWINE_CHIMERAL("saqawine chimeral", ItemDefinitionEnumCategoryMapper.BEAST),
    SAQAWINE_COBRA("saqawine cobra", ItemDefinitionEnumCategoryMapper.BEAST),
    SAQAWINE_RETCH("saqawine retch", ItemDefinitionEnumCategoryMapper.BEAST),
    SAQAWINE_RHOA("saqawine rhoa", ItemDefinitionEnumCategoryMapper.BEAST),
    SAVAGE_CRAB("savage crab", ItemDefinitionEnumCategoryMapper.BEAST),
    SCUM_CRAWLER("scum crawler", ItemDefinitionEnumCategoryMapper.BEAST),
    SEWAGE_CRAWLER("sewage crawler", ItemDefinitionEnumCategoryMapper.BEAST),
    SHACKLED_HELLION("shackled hellion", ItemDefinitionEnumCategoryMapper.BEAST),
    SHAGGY_MONSTROSITY("shaggy monstrosity", ItemDefinitionEnumCategoryMapper.BEAST),
    SKELETAL_BEAST("skeletal beast", ItemDefinitionEnumCategoryMapper.BEAST),
    SLIMY_NEMESIS("slimy nemesis", ItemDefinitionEnumCategoryMapper.BEAST),
    SNOW_WOLF("snow wolf", ItemDefinitionEnumCategoryMapper.BEAST),
    SOULLESS_WATCHER("soulless watcher", ItemDefinitionEnumCategoryMapper.BEAST),
    SPINDLE_SPIDER("spindle spider", ItemDefinitionEnumCategoryMapper.BEAST),
    SPINE_SERPENT("spine serpent", ItemDefinitionEnumCategoryMapper.BEAST),
    SPITTING_PARASITE("spitting parasite", ItemDefinitionEnumCategoryMapper.BEAST),
    STYGIAN_APE("stygian ape", ItemDefinitionEnumCategoryMapper.BEAST),
    SULPHURIC_SCORPION("sulphuric scorpion", ItemDefinitionEnumCategoryMapper.BEAST),
    SULPHURSPAWN("sulphurspawn", ItemDefinitionEnumCategoryMapper.BEAST),
    TALON_ARCHER("talon archer", ItemDefinitionEnumCategoryMapper.BEAST),
    TERCEL_RHOA("tercel rhoa", ItemDefinitionEnumCategoryMapper.BEAST),
    TOXIC_CRAWLER("toxic crawler", ItemDefinitionEnumCategoryMapper.BEAST),
    WASTE_LURCHER("waste lurcher", ItemDefinitionEnumCategoryMapper.BEAST),
    WEBBED_SPIDER("webbed spider", ItemDefinitionEnumCategoryMapper.BEAST),
    WILD_RHEX("wild rhex", ItemDefinitionEnumCategoryMapper.BEAST),
    VENOMOUS_SPAWN("venomous spawn", ItemDefinitionEnumCategoryMapper.BEAST),
    DREAD_PRIMATE("dread primate", ItemDefinitionEnumCategoryMapper.BEAST),
    ENSLAVED_HELLION("enslaved hellion", ItemDefinitionEnumCategoryMapper.BEAST),
    SINGING_SIREN("singing siren", ItemDefinitionEnumCategoryMapper.BEAST),
    VIRULENT_SPIDER("virulent spider", ItemDefinitionEnumCategoryMapper.BEAST),
    BONE_CRUNCHER("bone cruncher", ItemDefinitionEnumCategoryMapper.BEAST),
    CRAICIC_SAND_SPITTER("craicic sand spitter", ItemDefinitionEnumCategoryMapper.BEAST),
    FENUMAL_SCRABBLER("fenumal scrabbler", ItemDefinitionEnumCategoryMapper.BEAST),
    FARRIC_GARGANTUAN("farric gargantuan", ItemDefinitionEnumCategoryMapper.BEAST),
    CRAICIC_SQUID("craicic squid", ItemDefinitionEnumCategoryMapper.BEAST),
    OMEN_OF_THE_JEWELLER("omen of the jeweller",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_REFRESHMENT("omen of refreshment",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_RETURN("omen of return",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_ADRENALINE("omen of adrenaline",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_BLANCHING("omen of blanching",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_DEATHS_DOOR("omen of death's door",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_FORTUNE("omen of fortune",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_REVENGE("omen of revenge",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_AMELIORATION("omen of amelioration",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_ACCELERATION("omen of acceleration",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_BEQUEATHAL("omen of bequeathal",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_BRILLIANCE("omen of brilliance",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_RESURGENCE("omen of resurgence",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_CONNECTIONS("omen of connections",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_DEATHDANCING("omen of deathdancing",ItemDefinitionEnumCategoryMapper.OMEN),
    OMEN_OF_THE_SOUL_DEVOURER("omen of the soul devourer",ItemDefinitionEnumCategoryMapper.OMEN),
    TATTOO_OF_THE_HINEKORA_WARRIOR("tattoo of the hinekora warrior",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_SKY("honoured tattoo of the sky",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_HINEKORA_WARMONGER("tattoo of the hinekora warmonger",ItemDefinitionEnumCategoryMapper.TATTOO),
    LOYALTY_TATTOO_OF_MAATA("loyalty tattoo of maata",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TASALIO_WARRIOR("tattoo of the tasalio warrior",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TASALIO_TIDESHIFTER("tattoo of the tasalio tideshifter",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_HINEKORA_SHAMAN("tattoo of the hinekora shaman",ItemDefinitionEnumCategoryMapper.TATTOO),
    LOYALTY_TATTOO_OF_TAWHANUKU("loyalty tattoo of tawhanuku",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_AROHONGUI_SCOUT("tattoo of the arohongui scout",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_TUATARA("honoured tattoo of the tuatara",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_KITAVA_WARRIOR("tattoo of the kitava warrior",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_KITAVA_HEART_EATER("tattoo of the kitava heart eater",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_BERSERKER("honoured tattoo of the berserker",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_RONGOKURAI_TURTLE("tattoo of the rongokurai turtle",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_WARLORD("honoured tattoo of the warlord",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_RONGOKURAI_WARRIOR("tattoo of the rongokurai warrior",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_NGAMAHU_WARMONGER("tattoo of the ngamahu warmonger",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_KITAVA_BLOOD_DRINKER("tattoo of the kitava blood drinker",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_HINEKORA_DEATHWARDEN("tattoo of the hinekora deathwarden",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_DOVE("honoured tattoo of the dove",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_VALAKO_MAKANGA("tattoo of the valako makanga",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TUKOHAMA_MAKANGA("tattoo of the tukohama makanga",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_NGAMAHU_SHAMAN("tattoo of the ngamahu shaman",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_BARBARIAN("honoured tattoo of the barbarian",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_RONGOKURAI_GUARD("tattoo of the rongokurai guard",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_MOUNTAIN("honoured tattoo of the mountain",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_RAMAKO_ARCHER("tattoo of the ramako archer",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TAWHOA_WARRIOR("tattoo of the tawhoa warrior",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_PA("honoured tattoo of the pa",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TAWHOA_HERBALIST("tattoo of the tawhoa herbalist",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TUKOHAMA_BRAWLER("tattoo of the tukohama brawler",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TAWHOA_NATURALIST("tattoo of the tawhoa naturalist",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_VALAKO_WARRIOR("tattoo of the valako warrior",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_HATUNGO("honoured tattoo of the hatungo",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TUKOHAMA_WARCALLER("tattoo of the tukohama warcaller",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_NGAMAHU_MAKANGA("tattoo of the ngamahu makanga",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_RAMAKO_SCOUT("tattoo of the ramako scout",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_AROHONGUI_MOONWARDEN("tattoo of the arohongui moonwarden",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_FLOOD("honoured tattoo of the flood",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_RAMAKO_SNIPER("tattoo of the ramako sniper",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_RAMAKO_FLEETFOOT("tattoo of the ramako fleetfoot",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_HUNTER("honoured tattoo of the hunter",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TAWHOA_MAKANGA("tattoo of the tawhoa makanga",ItemDefinitionEnumCategoryMapper.TATTOO),
    LOYALTY_TATTOO_OF_AHUANA("loyalty tattoo of ahuana",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TAWHOA_SCOUT("tattoo of the tawhoa scout",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_NGAMAHU_WARRIOR("tattoo of the ngamahu warrior",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_RAMAKO_MAKANGA("tattoo of the ramako makanga",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_NGAMAHU_FIREWALKER("tattoo of the ngamahu firewalker",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_KITAVA_REBEL("tattoo of the kitava rebel",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TASALIO_BLADEDANCER("tattoo of the tasalio bladedancer",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_AROHONGUI_WARMONGER("tattoo of the arohongui warmonger",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_VALAKO_SHAMAN("tattoo of the valako shaman",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_HINEKORA_MAKANGA("tattoo of the hinekora makanga",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TUKOHAMA_WARRIOR("tattoo of the tukohama warrior",ItemDefinitionEnumCategoryMapper.TATTOO),
    LOYALTY_TATTOO_OF_IKIAHO("loyalty tattoo of ikiaho",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_AROHONGUI_SHAMAN("tattoo of the arohongui shaman",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TASALIO_SCOUT("tattoo of the tasalio scout",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TUKOHAMA_SHAMAN("tattoo of the tukohama shaman",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_WISE("honoured tattoo of the wise",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_TURTLE("honoured tattoo of the turtle",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_NGAMAHU_WOODCARVER("tattoo of the ngamahu woodcarver",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TUKOHAMA_WARMONGER("tattoo of the tukohama warmonger",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_RONGOKURAI_MAKANGA("tattoo of the rongokurai makanga",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_FLOCK("honoured tattoo of the flock",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TASALIO_MAKANGA("tattoo of the tasalio makanga",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_KITAVA_MAKANGA("tattoo of the kitava makanga",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_RAMAKO_SHAMAN("tattoo of the ramako shaman",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TASALIO_SHAMAN("tattoo of the tasalio shaman",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_RONGOKURAI_GOLIATH("tattoo of the rongokurai goliath",ItemDefinitionEnumCategoryMapper.TATTOO),
    LOYALTY_TATTOO_OF_KILOAVA("loyalty tattoo of kiloava",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_VALAKO_SCOUT("tattoo of the valako scout",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_AROHONGUI_MAKANGA("tattoo of the arohongui makanga",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_HINEKORA_STORYTELLER("tattoo of the hinekora storyteller",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_PILLAGER("honoured tattoo of the pillager",ItemDefinitionEnumCategoryMapper.TATTOO),
    LOYALTY_TATTOO_OF_RAKIATA("loyalty tattoo of rakiata",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_KITAVA_SHAMAN("tattoo of the kitava shaman",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_RONGOKURAI_BRUTE("tattoo of the rongokurai brute",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_STORM("honoured tattoo of the storm",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_TAWHOA_SHAMAN("tattoo of the tawhoa shaman",ItemDefinitionEnumCategoryMapper.TATTOO),
    LOYALTY_TATTOO_OF_KAOM("loyalty tattoo of kaom",ItemDefinitionEnumCategoryMapper.TATTOO),
    LOYALTY_TATTOO_OF_UTULA("loyalty tattoo of utula",ItemDefinitionEnumCategoryMapper.TATTOO),
    LOYALTY_TATTOO_OF_AKOYA("loyalty tattoo of akoya",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_VALAKO_SHIELDBEARER("tattoo of the valako shieldbearer",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_VALAKO_STORMRIDER("tattoo of the valako stormrider",ItemDefinitionEnumCategoryMapper.TATTOO),
    HONOURED_TATTOO_OF_THE_OAK("honoured tattoo of the oak",ItemDefinitionEnumCategoryMapper.TATTOO),
    LOYALTY_TATTOO_OF_KAHUTUROA("loyalty tattoo of kahuturoa",ItemDefinitionEnumCategoryMapper.TATTOO),
    TATTOO_OF_THE_AROHONGUI_WARRIOR("tattoo of the arohongui warrior",ItemDefinitionEnumCategoryMapper.TATTOO),
    ;

    private final String name;
    private final ItemDefinitionEnumCategoryMapper category;

    ItemDefinitionEnum(String name, ItemDefinitionEnumCategoryMapper category) {
        this.name = name;
        this.category = category;
    }

    public ItemDefinitionEnumCategoryMapper getCategory() {
        return category;
    }

    public String getName() {
        return name;
    }

    public static ItemDefinitionEnumCategoryMapper getCategoryFromName(String name) {
        return fromString(name).getCategory();
    }

    private static final Map<String, ItemDefinitionEnum> stringMap;

    public static ItemDefinitionEnum fromString(String value) {
        if(!ItemDefinitionEnum.contains(value.toLowerCase())) {
            throw new IllegalArgumentException(String.format("Unrecognized enum value, got %s", value.toLowerCase()));
        }

        return stringMap.get(value.toLowerCase());
    }

    public static boolean contains(String name) {
        return stringMap.containsKey(name.toLowerCase());
    }

    static {
        stringMap = Arrays.stream(values()).collect(Collectors.toMap(ItemDefinitionEnum::getName, Function.identity()));
    }
}
