package com.exileeconomics.definitions;


import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;


public enum ItemDefinitionEnum {

    WEALTH_AND_POWER("wealth and power", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    LUMINOUS_TROVE("luminous trove", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    SOMETHING_DARK("something dark", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    A_FAMILIAR_CALL("a familiar call", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ONE_THAT_GOT_AWAY("the one that got away", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    A_MODEST_REQUEST("a modest request", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ARTIST("the artist", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_STRATEGIST("the strategist", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_FISHMONGER("the fishmonger", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_NURSE("the nurse", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_LEVIATHAN("the leviathan", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_BITTER_BLOSSOM("the bitter blossom", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    CHOKING_GUILT("choking guilt", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_CHEATER("the cheater", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    IMPERFECT_MEMORIES("imperfect memories", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    PROMETHEUS_ARMOURY("prometheus' armoury", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    SUCCOR_OF_THE_SINLESS("succor of the sinless", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ASPIRANT("the aspirant", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_GULF("the gulf", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    HOME("home", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    DRAPED_IN_DREAMS("draped in dreams", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SCOUT("the scout", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    GIFT_OF_ASENATH("gift of asenath", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    UNREQUITED_LOVE("unrequited love", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_DOCTOR("the doctor", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ASTROMANCER("the astromancer", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    BEAUTY_THROUGH_DEATH("beauty through death", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_INSANE_CAT("the insane cat", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_AWAKENED("the awakened", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    ALLURING_BOUNTY("alluring bounty", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    REMEMBRANCE("remembrance", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    BROKEN_PROMISES("broken promises", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_FIEND("the fiend", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    HOUSE_OF_MIRRORS("house of mirrors", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    MONOCHROME("monochrome", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_VAST("the vast", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ENLIGHTENED("the enlightened", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_OLD_MAN("the old man", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    DARKER_HALF("darker half", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SHORTCUT("the shortcut", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    DIVINE_BEAUTY("divine beauty", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SOUL("the soul", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    BROTHERS_GIFT("brother's gift", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    DUALITY("duality", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    DORYANIS_EPIPHANY("doryani's epiphany", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    A_FATE_WORSE_THAN_DEATH("a fate worse than death", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ETERNAL_WAR("the eternal war", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    FRAGMENT_OF_ERADICATION("fragment of eradication", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SACRIFICE("the sacrifice", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_PRICE_OF_LOYALTY("the price of loyalty", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    SEVEN_YEARS_BAD_LUCK("seven years bad luck", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    WINTERS_EMBRACE("winter's embrace", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    ETERNAL_BONDS("eternal bonds", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    DESECRATED_VIRTUE("desecrated virtue", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_DRAGONS_HEART("the dragon's heart", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    REBIRTH("rebirth", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    LOVE_THROUGH_ICE("love through ice", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    MAGNUM_OPUS("magnum opus", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_TUMBLEWEED("the tumbleweed", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    FATEFUL_MEETING("fateful meeting", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_CHOSEN("the chosen", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SEPHIROT("the sephirot", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    MATRYOSHKA("matryoshka", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_EYE_OF_TERROR("the eye of terror", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_HOOK("the hook", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_DESTINATION("the destination", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_GARISH_POWER("the garish power", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    FURTHER_INVENTION("further invention", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_ENDLESS_DARKNESS("the endless darkness", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    BROTHERS_STASH("brother's stash", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_PRICE_OF_DEVOTION("the price of devotion", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_IMMORTAL("the immortal", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_PATIENT("the patient", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_RABBITS_FOOT("the rabbit's foot", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_APOTHECARY("the apothecary", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SAMURAIS_EYE("the samurai's eye", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_SHIELDBEARER("the shieldbearer", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    GEMCUTTERS_MERCY("gemcutter's mercy", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_GREATEST_INTENTIONS("the greatest intentions", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_LAST_ONE_STANDING("the last one standing", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),
    THE_DEMON("the demon", ItemDefinitionEnumCategoryMapper.DIVINATION_CARD),

    WINGED_TORMENT_SCARAB("winged torment scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_SHAPER_SCARAB("gilded shaper scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_SULPHITE_SCARAB("winged sulphite scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_LEGION_SCARAB("gilded legion scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_BREACH_SCARAB("rusted breach scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_HARBINGER_SCARAB("winged harbinger scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_BLIGHT_SCARAB("rusted blight scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_METAMORPH_SCARAB("polished metamorph scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_TORMENT_SCARAB("gilded torment scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_EXPEDITION_SCARAB("winged expedition scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_LEGION_SCARAB("rusted legion scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_ELDER_SCARAB("rusted elder scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_CARTOGRAPHY_SCARAB("polished cartography scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_TORMENT_SCARAB("rusted torment scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_DIVINATION_SCARAB("rusted divination scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_AMBUSH_SCARAB("gilded ambush scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_DIVINATION_SCARAB("polished divination scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_SULPHITE_SCARAB("gilded sulphite scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_ELDER_SCARAB("gilded elder scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_ABYSS_SCARAB("polished abyss scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_LEGION_SCARAB("polished legion scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_RELIQUARY_SCARAB("gilded reliquary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_BLIGHT_SCARAB("winged blight scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_SHAPER_SCARAB("winged shaper scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    TORMENT_SCARAB("torment scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_DIVINATION_SCARAB("gilded divination scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_RELIQUARY_SCARAB("polished reliquary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_BESTIARY_SCARAB("winged bestiary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_ABYSS_SCARAB("rusted abyss scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_AMBUSH_SCARAB("rusted ambush scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_SHAPER_SCARAB("rusted shaper scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_ELDER_SCARAB("polished elder scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_ABYSS_SCARAB("gilded abyss scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_CARTOGRAPHY_SCARAB("winged cartography scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_LEGION_SCARAB("winged legion scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_BREACH_SCARAB("gilded breach scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_AMBUSH_SCARAB("polished ambush scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_SHAPER_SCARAB("polished shaper scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_BREACH_SCARAB("polished breach scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_METAMORPH_SCARAB("gilded metamorph scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_BLIGHT_SCARAB("polished blight scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_BESTIARY_SCARAB("gilded bestiary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_ABYSS_SCARAB("winged abyss scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_AMBUSH_SCARAB("winged ambush scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_HARBINGER_SCARAB("rusted harbinger scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_HARBINGER_SCARAB("gilded harbinger scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_SULPHITE_SCARAB("rusted sulphite scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_DIVINATION_SCARAB("winged divination scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_CARTOGRAPHY_SCARAB("rusted cartography scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_ELDER_SCARAB("winged elder scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_SULPHITE_SCARAB("polished sulphite scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_METAMORPH_SCARAB("rusted metamorph scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_RELIQUARY_SCARAB("winged reliquary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_EXPEDITION_SCARAB("polished expedition scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_EXPEDITION_SCARAB("rusted expedition scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_CARTOGRAPHY_SCARAB("gilded cartography scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_BESTIARY_SCARAB("polished bestiary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_BREACH_SCARAB("winged breach scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_EXPEDITION_SCARAB("gilded expedition scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_BESTIARY_SCARAB("rusted bestiary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    POLISHED_HARBINGER_SCARAB("polished harbinger scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    WINGED_METAMORPH_SCARAB("winged metamorph scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    GILDED_BLIGHT_SCARAB("gilded blight scarab", ItemDefinitionEnumCategoryMapper.SCARAB),
    RUSTED_RELIQUARY_SCARAB("rusted reliquary scarab", ItemDefinitionEnumCategoryMapper.SCARAB),

    SCREAMING_ESSENCE_OF_ENVY("screaming essence of envy", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_ANGER("deafening essence of anger", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_HATRED("deafening essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_RAGE("screaming essence of rage", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_FEAR("screaming essence of fear", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_LOATHING("deafening essence of loathing", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_RAGE("weeping essence of rage", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_HATRED("shrieking essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_ENVY("deafening essence of envy", ItemDefinitionEnumCategoryMapper.ESSENCE),
    ESSENCE_OF_DELIRIUM("essence of delirium", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_FEAR("deafening essence of fear", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_ZEAL("shrieking essence of zeal", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_CONTEMPT("shrieking essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_WOE("wailing essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_WRATH("wailing essence of wrath", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_ANGUISH("shrieking essence of anguish", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_SUFFERING("shrieking essence of suffering", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_SCORN("deafening essence of scorn", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_DREAD("deafening essence of dread", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_RAGE("wailing essence of rage", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_WRATH("weeping essence of wrath", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_ANGER("wailing essence of anger", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_ANGER("screaming essence of anger", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_ZEAL("screaming essence of zeal", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_WOE("muttering essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_SUFFERING("deafening essence of suffering", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_CONTEMPT("muttering essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_SUFFERING("wailing essence of suffering", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_ANGER("muttering essence of anger", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_DREAD("shrieking essence of dread", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_DREAD("screaming essence of dread", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_FEAR("muttering essence of fear", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_SPITE("wailing essence of spite", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_WRATH("deafening essence of wrath", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_SPITE("shrieking essence of spite", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WHISPERING_ESSENCE_OF_GREED("whispering essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_SPITE("screaming essence of spite", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_ANGER("shrieking essence of anger", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_WOE("deafening essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_SORROW("wailing essence of sorrow", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_LOATHING("shrieking essence of loathing", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WHISPERING_ESSENCE_OF_WOE("whispering essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_ENVY("shrieking essence of envy", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_FEAR("shrieking essence of fear", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WHISPERING_ESSENCE_OF_HATRED("whispering essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_TORMENT("screaming essence of torment", ItemDefinitionEnumCategoryMapper.ESSENCE),
    ESSENCE_OF_HORROR("essence of horror", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_SUFFERING("screaming essence of suffering", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_GREED("muttering essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_SCORN("shrieking essence of scorn", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_SORROW("muttering essence of sorrow", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_ANGER("weeping essence of anger", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_TORMENT("shrieking essence of torment", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_DOUBT("screaming essence of doubt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_GREED("weeping essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_CONTEMPT("wailing essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_ZEAL("deafening essence of zeal", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_DOUBT("shrieking essence of doubt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_ANGUISH("deafening essence of anguish", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_WRATH("screaming essence of wrath", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_GREED("screaming essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_WRATH("shrieking essence of wrath", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_ANGUISH("wailing essence of anguish", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_SPITE("deafening essence of spite", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_TORMENT("weeping essence of torment", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_ANGUISH("screaming essence of anguish", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_FEAR("wailing essence of fear", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_TORMENT("wailing essence of torment", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_CONTEMPT("weeping essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_RAGE("deafening essence of rage", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_GREED("shrieking essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_GREED("wailing essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_DOUBT("weeping essence of doubt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_HATRED("wailing essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_SCORN("screaming essence of scorn", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_FEAR("weeping essence of fear", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_HATRED("muttering essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_HATRED("weeping essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_HATRED("screaming essence of hatred", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_ZEAL("wailing essence of zeal", ItemDefinitionEnumCategoryMapper.ESSENCE),
    ESSENCE_OF_INSANITY("essence of insanity", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_GREED("deafening essence of greed", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_LOATHING("screaming essence of loathing", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WHISPERING_ESSENCE_OF_CONTEMPT("whispering essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_DOUBT("deafening essence of doubt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_WOE("screaming essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_RAGE("shrieking essence of rage", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_CONTEMPT("deafening essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_SORROW("shrieking essence of sorrow", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_MISERY("screaming essence of misery", ItemDefinitionEnumCategoryMapper.ESSENCE),
    ESSENCE_OF_HYSTERIA("essence of hysteria", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_WOE("weeping essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    MUTTERING_ESSENCE_OF_TORMENT("muttering essence of torment", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_SORROW("screaming essence of sorrow", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_SORROW("weeping essence of sorrow", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_LOATHING("wailing essence of loathing", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_MISERY("deafening essence of misery", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SCREAMING_ESSENCE_OF_CONTEMPT("screaming essence of contempt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WAILING_ESSENCE_OF_DOUBT("wailing essence of doubt", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_SORROW("deafening essence of sorrow", ItemDefinitionEnumCategoryMapper.ESSENCE),
    WEEPING_ESSENCE_OF_SUFFERING("weeping essence of suffering", ItemDefinitionEnumCategoryMapper.ESSENCE),
    DEAFENING_ESSENCE_OF_TORMENT("deafening essence of torment", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_WOE("shrieking essence of woe", ItemDefinitionEnumCategoryMapper.ESSENCE),
    SHRIEKING_ESSENCE_OF_MISERY("shrieking essence of misery", ItemDefinitionEnumCategoryMapper.ESSENCE),
    REMNANT_OF_CORRUPTION("remnant of corruption", ItemDefinitionEnumCategoryMapper.ESSENCE),
    EXOTIC_COINAGE("exotic coinage", ItemDefinitionEnumCategoryMapper.ARTIFACT),
    BURIAL_MEDALLION("burial medallion", ItemDefinitionEnumCategoryMapper.ARTIFACT),
    SCRAP_METAL("scrap metal", ItemDefinitionEnumCategoryMapper.ARTIFACT),
    ASTRAGALI("astragali", ItemDefinitionEnumCategoryMapper.ARTIFACT),
    TAINTED_ORB_OF_FUSING("tainted orb of fusing", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    TAINTED_MYTHIC_ORB("tainted mythic orb", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    TAINTED_BLESSING("tainted blessing", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    TAINTED_CHAOS_ORB("tainted chaos orb", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    TAINTED_JEWELLERS_ORB("tainted jeweller's orb", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    TAINTED_OIL("tainted oil", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    TAINTED_EXALTED_ORB("tainted exalted orb", ItemDefinitionEnumCategoryMapper.TAINTED_CURRENCY),
    WILD_CRYSTALLISED_LIFEFORCE("wild crystallised lifeforce", ItemDefinitionEnumCategoryMapper.LIFEFORCE),
    PRIMAL_CRYSTALLISED_LIFEFORCE("primal crystallised lifeforce", ItemDefinitionEnumCategoryMapper.LIFEFORCE),
    SACRED_CRYSTALLISED_LIFEFORCE("sacred crystallised lifeforce", ItemDefinitionEnumCategoryMapper.LIFEFORCE),
    VIVID_CRYSTALLISED_LIFEFORCE("vivid crystallised lifeforce", ItemDefinitionEnumCategoryMapper.LIFEFORCE),
    AMORPHOUS_DELIRIUM_ORB("amorphous delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    BLIGHTED_DELIRIUM_ORB("blighted delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    FINE_DELIRIUM_ORB("fine delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    ABYSSAL_DELIRIUM_ORB("abyssal delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    OBSCURED_DELIRIUM_ORB("obscured delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    FOREBODING_DELIRIUM_ORB("foreboding delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    ARMOURSMITHS_DELIRIUM_ORB("armoursmith's delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    IMPERIAL_DELIRIUM_ORB("imperial delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    BLACKSMITHS_DELIRIUM_ORB("blacksmith's delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    THAUMATURGES_DELIRIUM_ORB("thaumaturge's delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    SKITTERING_DELIRIUM_ORB("skittering delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    FRAGMENTED_DELIRIUM_ORB("fragmented delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    DIVINERS_DELIRIUM_ORB("diviner's delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    SINGULAR_DELIRIUM_ORB("singular delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    FOSSILISED_DELIRIUM_ORB("fossilised delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    CARTOGRAPHERS_DELIRIUM_ORB("cartographer's delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    WHISPERING_DELIRIUM_ORB("whispering delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    TIMELESS_DELIRIUM_ORB("timeless delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    JEWELLERS_DELIRIUM_ORB("jeweller's delirium orb", ItemDefinitionEnumCategoryMapper.DELIRIUM_ORB),
    XOPHS_BREACHSTONE("xoph's breachstone", ItemDefinitionEnumCategoryMapper.BREACHSTONE),
    UULNETOLS_BREACHSTONE("uul-netol's breachstone", ItemDefinitionEnumCategoryMapper.BREACHSTONE),
    ESHS_BREACHSTONE("esh's breachstone", ItemDefinitionEnumCategoryMapper.BREACHSTONE),
    CHAYULAS_FLAWLESS_BREACHSTONE("chayula's flawless breachstone", ItemDefinitionEnumCategoryMapper.BREACHSTONE),
    TULS_BREACHSTONE("tul's breachstone", ItemDefinitionEnumCategoryMapper.BREACHSTONE),
    CHAYULAS_BREACHSTONE("chayula's breachstone", ItemDefinitionEnumCategoryMapper.BREACHSTONE),
    GOLDEN_OIL("golden oil", ItemDefinitionEnumCategoryMapper.OIL),
    OPALESCENT_OIL("opalescent oil", ItemDefinitionEnumCategoryMapper.OIL),
    BLACK_OIL("black oil", ItemDefinitionEnumCategoryMapper.OIL),
    CRIMSON_OIL("crimson oil", ItemDefinitionEnumCategoryMapper.OIL),
    SILVER_OIL("silver oil", ItemDefinitionEnumCategoryMapper.OIL),
    REFLECTIVE_OIL("reflective oil", ItemDefinitionEnumCategoryMapper.OIL),

    PRISTINE_FOSSIL("pristine fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    GLYPHIC_FOSSIL("glyphic fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    ABERRANT_FOSSIL("aberrant fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    PRISMATIC_FOSSIL("prismatic fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    DENSE_FOSSIL("dense fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    SCORCHED_FOSSIL("scorched fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    LUCENT_FOSSIL("lucent fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    BLOODSTAINED_FOSSIL("bloodstained fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    TANGLED_FOSSIL("tangled fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    METALLIC_FOSSIL("metallic fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    FACETED_FOSSIL("faceted fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    JAGGED_FOSSIL("jagged fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    SERRATED_FOSSIL("serrated fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    SANCTIFIED_FOSSIL("sanctified fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    BOUND_FOSSIL("bound fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    GILDED_FOSSIL("gilded fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    AETHERIC_FOSSIL("aetheric fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    SHUDDERING_FOSSIL("shuddering fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    FUNDAMENTAL_FOSSIL("fundamental fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    PERFECT_FOSSIL("perfect fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    FRIGID_FOSSIL("frigid fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    HOLLOW_FOSSIL("hollow fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    FRACTURED_FOSSIL("fractured fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    DEFT_FOSSIL("deft fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    CORRODED_FOSSIL("corroded fossil", ItemDefinitionEnumCategoryMapper.FOSSIL),
    FRAGMENT_OF_ENSLAVEMENT("fragment of enslavement", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_THE_HYDRA("fragment of the hydra", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_THE_PHOENIX("fragment of the phoenix", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_PURIFICATION("fragment of purification", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_THE_CHIMERA("fragment of the chimera", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_TERROR("fragment of terror", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_EMPTINESS("fragment of emptiness", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_THE_MINOTAUR("fragment of the minotaur", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_SHAPE("fragment of shape", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_KNOWLEDGE("fragment of knowledge", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    FRAGMENT_OF_CONSTRICTION("fragment of constriction", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    DROXS_CREST("drox's crest", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    BARANS_CREST("baran's crest", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    VERITANIAS_CREST("veritania's crest", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    ALHEZMINS_CREST("al-hezmin's crest", ItemDefinitionEnumCategoryMapper.FRAGMENT),
    VIAL_OF_THE_GHOST("vial of the ghost", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_THE_RITUAL("vial of the ritual", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_SUMMONING("vial of summoning", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_AWAKENING("vial of awakening", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_CONSEQUENCE("vial of consequence", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_SACRIFICE("vial of sacrifice", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_TRANSCENDENCE("vial of transcendence", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_DOMINANCE("vial of dominance", ItemDefinitionEnumCategoryMapper.VIAL),
    VIAL_OF_FATE("vial of fate", ItemDefinitionEnumCategoryMapper.VIAL),
    MIRROR_OF_KALANDRA("mirror of kalandra", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_CHANCE("orb of chance", ItemDefinitionEnumCategoryMapper.CURRENCY),
    HUNTERS_EXALTED_ORB("hunter's exalted orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ELDRITCH_EXALTED_ORB("eldritch exalted orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ELDRITCH_ORB_OF_ANNULMENT("eldritch orb of annulment", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ANCIENT_ORB("ancient orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    REGAL_ORB("regal orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    GRAND_ELDRITCH_ICHOR("grand eldritch ichor", ItemDefinitionEnumCategoryMapper.CURRENCY),
    EXALTED_ORB("exalted orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_SCOURING("orb of scouring", ItemDefinitionEnumCategoryMapper.CURRENCY),
    GEMCUTTERS_PRISM("gemcutter's prism", ItemDefinitionEnumCategoryMapper.CURRENCY),
    FRACTURING_ORB("fracturing orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    AWAKENED_SEXTANT("awakened sextant", ItemDefinitionEnumCategoryMapper.CURRENCY),
    REDEEMERS_EXALTED_ORB("redeemer's exalted orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    STACKED_DECK("stacked deck", ItemDefinitionEnumCategoryMapper.CURRENCY),
    WARLORDS_EXALTED_ORB("warlord's exalted orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    GIFT_TO_THE_GODDESS("gift to the goddess", ItemDefinitionEnumCategoryMapper.CURRENCY),
    THE_MAVENS_WRIT("the maven's writ", ItemDefinitionEnumCategoryMapper.CURRENCY),
    DEDICATION_TO_THE_GODDESS("dedication to the goddess", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ENKINDLING_ORB("enkindling orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    CRUSADERS_EXALTED_ORB("crusader's exalted orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    BLESSED_ORB("blessed orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ELDRITCH_CHAOS_ORB("eldritch chaos orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    GREATER_ELDRITCH_ICHOR("greater eldritch ichor", ItemDefinitionEnumCategoryMapper.CURRENCY),
    VEILED_CHAOS_ORB("veiled chaos orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    CHAOS_ORB("chaos orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_UNMAKING("orb of unmaking", ItemDefinitionEnumCategoryMapper.CURRENCY),
    SACRED_BLOSSOM("sacred blossom", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_ANNULMENT("orb of annulment", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ELEVATED_SEXTANT("elevated sextant", ItemDefinitionEnumCategoryMapper.CURRENCY),
    VAAL_ORB("vaal orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_REGRET("orb of regret", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_FUSING("orb of fusing", ItemDefinitionEnumCategoryMapper.CURRENCY),
    MIRROR_SHARD("mirror shard", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_ALTERATION("orb of alteration", ItemDefinitionEnumCategoryMapper.CURRENCY),
    GLASSBLOWERS_BAUBLE("glassblower's bauble", ItemDefinitionEnumCategoryMapper.CURRENCY),
    GREATER_ELDRITCH_EMBER("greater eldritch ember", ItemDefinitionEnumCategoryMapper.CURRENCY),
    GRAND_ELDRITCH_EMBER("grand eldritch ember", ItemDefinitionEnumCategoryMapper.CURRENCY),
    ORB_OF_ALCHEMY("orb of alchemy", ItemDefinitionEnumCategoryMapper.CURRENCY),
    EXCEPTIONAL_ELDRITCH_ICHOR("exceptional eldritch ichor", ItemDefinitionEnumCategoryMapper.CURRENCY),
    SACRED_ORB("sacred orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    DIVINE_ORB("divine orb", ItemDefinitionEnumCategoryMapper.CURRENCY),
    EXCEPTIONAL_ELDRITCH_EMBER("exceptional eldritch ember", ItemDefinitionEnumCategoryMapper.CURRENCY),
    INSTILLING_ORB("instilling orb", ItemDefinitionEnumCategoryMapper.CURRENCY)
    ;

    private final String name;
    private final ItemDefinitionEnumCategoryMapper category;

    ItemDefinitionEnum(String name, ItemDefinitionEnumCategoryMapper category) {
        this.name = name;
        this.category = category;
    }

    public ItemDefinitionEnumCategoryMapper getCategory() {
        return category;
    }

    public String getName() {
        return name;
    }

    public static ItemDefinitionEnumCategoryMapper getCategoryFromName(String name) {
        return fromString(name).getCategory();
    }

    private static final Map<String, ItemDefinitionEnum> stringMap;

    public static ItemDefinitionEnum fromString(String value) {
        if(!ItemDefinitionEnum.contains(value.toLowerCase())) {
            throw new IllegalArgumentException(String.format("Unrecognized enum value, got %s", value.toLowerCase()));
        }

        return stringMap.get(value.toLowerCase());
    }

    public static boolean contains(String name) {
        return stringMap.containsKey(name.toLowerCase());
    }

    static {
        stringMap = Arrays.stream(values()).collect(Collectors.toMap(ItemDefinitionEnum::getName, Function.identity()));
    }
}
